name: VariableSystem
version: '1.0'
main: cn.clexus.variableSystem.VariableSystem
api-version: '1.21.8'
loader: cn.clexus.variableSystem.PluginLoaderImpl
dependencies:
  server:
    PlaceholderAPI:
      load: BEFORE
      required: true